### PR TITLE
Implement some methods in `meta` and `helpers`

### PR DESCRIPTION
**Pull request by layerssss**
Hey, here I come with another patch of the weekend.

This made all `helper` methods available and "reduce/each" methods in "meta" available. These methods are used in most existing turf.js test code. It would be a good base for next step.

In terms of the next step, a low-hanging fruit would be methods of the "measurement" group.

### CODE REVIEW

**Comment by formigarafa** [comment]
I am planning to have a look at this tonight. Thank you.

**Comment by formigarafa** [comment]
Nice!

**Comment by formigarafa** [comment]
I an issue with area test.
I suspect there may be something related with float precision differences depending on architecture.
image

I am using macos do you use linux, @layerssss ?

**Comment by formigarafa** [comment]
It only happens with "polygon_holes" test for area function.

**Comment by layerssss** [comment]
Hey, that’s interesting because i’m indeed using linux. The original turf.js test code actually doesn’t have the fractional part of the result i thought it’s a js-ruby thing so i added it. Now it seems worth investigating why.

**Comment by layerssss** [comment]
@formigarafa It turns out the original turf.js test code cheated using `Math.round` and I missed that:

https://github.com/Turfjs/turf/blob/master/packages/turf-area/test.js#L25

**Comment by formigarafa** [comment]
I am getting seasoned with these macos floating point differences to linux.
Thank you for finding this. I will merge PR #18 later today and get a release asap.

**Pull request merged**
